### PR TITLE
update libevent to latest

### PR DESCRIPTION
**Pull request by theoden8**
https://github.com/clostra/newnode_private/blob/master/http.c#L236 error here

### CODE REVIEW

**Comment by ghazel** [comment]
It's sufficient to pass `NULL` as the last parameter to `evhttp_get_request()`. (it was *so close* to simplifying our code, but alas)

**Comment by theoden8** [comment]
i compiled newnode with this version, necessary changes here:

[8b6b961b256835451205d9a0941daa46f8a905aa](https://github.com/clostra/newnode_private/commit/8b6b961b256835451205d9a0941daa46f8a905aa)

**Comment by theoden8** [comment]
I'm happy with this, would you like to merge?

**Comment by ghazel** [comment]
> It's sufficient to pass `NULL` as the last parameter to `evhttp_get_request()`. (it was _so close_ to simplifying our code, but alas)

Actually, it is sufficient! https://github.com/libevent/libevent/issues/1268 solved the `fd` issue, two years after I worked around it https://github.com/clostra/newnode/commit/36be955d721c6d5ce6cc01731c39c2949d8d8e94 . So, hooray! https://github.com/clostra/newnode_private/commit/557109ce

**Pull request merged**
